version: '2'
services:
  base-project:
    image: test-docker
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - _JAVA_OPTIONS=-Xmx4096m -Xms1024m
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_SLEEP=0
      - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/base-db?createDatabaseIfNotExist=true
      - PARTNER_DATASOURCE_URL=jdbc:mysql://localhost:3306/base-db?createDatabaseIfNotExist=true
    ports:
      - 8080:80
    networks:
      - base_network
networks:
  base_network:
    external: true